### ISSUE TITLE
Feature request: add diaspora* as an additional social network

### ISSUE THREAD

**Issue by bgroenendal** [ArthurGareginyan/social-media-buttons-toolbar#2]
I'd like to put in a feature request for adding diaspora* (more info on: https://diasporafoundation.org) as an additional social network for others to follow you on.

Thanks in advance!

**Comment by ArthurGareginyan** [comment]
Done. Option for the diaspora* social network added to the version 4.3 of plugin. Enjoy! :)

**Comment by bgroenendal** [comment]
Just installed the update. The sharing works like a charm ^_^ Thanks a bunch!

**Comment by ArthurGareginyan** [comment]
@bgroenendal You're welcome! :)
